### ISSUE TITLE
Project Overview

### ISSUE THREAD

**Issue by hmontero1205** [crystalburritt/prj-rev-bwfs-dasmoto#1]
Overall, your work meets the project specifications -- great work!!!

I actually do not have any issues with your design. Spot on.
As for your style, I recommend putting more effort into spacing and commenting. Indentation should show a parent-child relationship. 
Also, why not put your images in a folder called `images`?

Other than that, keep it up!

**Comment by CBRRTT** [comment]
Great, makes sense. Thanks!
